---
title: "Analysis Driver"
format:
  html:
    toc: true
execute:
  echo: true
  warning: false
  message: false
---

```{r}
library(here)
library(tidyverse)
library(janitor)
library(lme4)
library(ggthemes)
library(stringr)
library(ggtext)

# Source the scripts that hold the real logic
source("R/reward_plots.R")
source("R/entropy_plots.R")
source("R/choice_frequencies.R")
source("R/correlations.R")
source("R/individual_behavior.R")
source("R/aggregate_behavior_distribution.R")
source("R/average_behavior_distribution.R")
source("R/individual_behavior_distribution.R")
source("R/experience_plots.R")
```
## Section 1: Participant Results

### Data

```{r}
experiment_name <- "transfer_bandits_choice_textbox"
version         <- "pilot_C"
run_individual_behavior <- FALSE

# Create the figure directory
fig_dir <- here("figures", experiment_name, version)
if (!dir.exists(fig_dir)) {
  dir.create(fig_dir, recursive = TRUE)
}

preprocessed_df <- read_csv(
  here(
    "data",
    experiment_name,
    version,
    paste0("preprocessed_data.csv")
  )
)
head(preprocessed_df)
```

### Participant Analyses

```{r}
# Choice Frequencies
p1 <- choice_frequencies(preprocessed_df, experiment_name, version, save = TRUE)
print(p1)

# Reward Plots
p2_human <- reward_plots(preprocessed_df, experiment_name, version, save = TRUE)
print(p2_human)

# Entropy Plots
p3_human <- entropy_plots(preprocessed_df, experiment_name, version, save = TRUE)
print(p3_human)

# Arm-Pulling Correlations
p4_human <- correlations(preprocessed_df, experiment_name, version, save = TRUE)
print(p4_human)

# Average Behavior Distribution Grid
p_dist_avg_human <- average_behavior_distribution(preprocessed_df, experiment_name, version, save = TRUE)
print(p_dist_avg_human)
```

### Individual Participant Analyses

```{r}
# Individual Participant Trajectories
if (run_individual_behavior) {
  individual_behavior(preprocessed_df, experiment_name, version, save = TRUE)
}

```

```{r}
# Individual Participant Distributions
if (run_individual_behavior) {
  individual_behavior_distribution(preprocessed_df, experiment_name, version, save = TRUE)
}
```

## Section 2: Model Results

### Data

```{r}
experiment_name <- "transfer_bandits_choice_textbox"
version         <- "hybrid_model"

model_df <- read_csv("/Users/juliomartinez/Documents/PhD/SocialBanditGuider/data/model_predictions/hybrid_model_predictions.csv")
model_df <- filter(model_df, learner_segment_input == "model" & beta_method == "theta_betas")
```

### Model Analyses
```{r}
# Reward Plots
p2_model <- reward_plots(model_df, experiment_name, version, save = TRUE)
print(p2_model)

# Entropy Plots
p3_model <- entropy_plots(model_df, experiment_name, version, save = TRUE)
print(p3_model)

# Arm-Pulling Correlations
p4_model <- correlations(model_df, experiment_name, version, save = TRUE)
print(p4_model)

# Average Behavior Distribution Grid
p_dist_avg_model <- average_behavior_distribution(model_df, experiment_name, version, save = TRUE)
print(p_dist_avg_model)

# Model Experience Predictions
p_experience <- experience_plots(model_df, experiment_name, version, save = TRUE)
print(p_experience)
```
